python scripts/run_piebench_batch.py \
    --backend flux1-kontext \
    --model-path /data_ljy/ll/weight/FLUX.1-Kontext-dev \
    --pie-root /data_ljy/ll/dataset/PIE_Bench \
    --output-dir /data_ljy/ll/output/results/PIE_Bench/flux_kontext_dev_havedit_t074_bhc64_w3_16 \
    --disable-trajectory-trust \
    --gpu-id 4 \
    --seed 42 \
    --threshold 0.74 \
    --subject-threshold 0.35 \
    --bhc-tau-low 0.64 \
    --bhc-tau-high 0.74 \
    --bhc-lambda-max 0.15 \
    --subject-select-mode largest \
    --subject-open-kernel 3 \
    --subject-close-kernel 1 \
    --subject-dilate-radius 1 \
    --background-discovery-step 16 \
    --subject-release-scale 0 \
    --alpha 1.0 \
    --beta 1 \
    --warmup-steps 3 \
    --overwrite