python scripts/run_piebench_batch.py \
    --model-path /data_ljy/ll/weight/black-forest-labs/FLUX.2-klein-base-9B \
    --pie-root /data_ljy/ll/dataset/PIE_Bench \
    --output-dir /data_ljy/ll/output/results/PIE_Bench/flux2_havedit_step10_t90_low0.60_no_bhc \
    --gpu-id 4 \
    --seed 42 \
    --threshold 0.90 \
    --bhc-tau-low 0.60 \
    --bhc-tau-high 0.90 \
    --bhc-lambda-max 0.15 \
    --disable-bhc \
    --hav-steps 10 \